### PR TITLE
fix #189 Boilerplate glitches

### LINKED ISSUE #189: Boilerplate glitches
Hat tip to BernardCornfeld for reporting (vastly) incorrect chain size estimates and start date.
image

### PR DESCRIPTION
**Pull request by walkjivefly**
Untested (due to lack of build environment) but should

fixes #189

### CODE REVIEW

**Comment by BlockMechanic** [comment]
Looks good , users would be scared off by the large numbers

File: src/chainparams.cpp [hunk 1]
```diff
@@ -155,8 +155,8 @@ class CMainParams : public CChainParams {
         nPruneAfterHeight = 100000;
         nAuxpowChainId = 20;
         nChainStallDuration = 60*60;
-        m_assumed_blockchain_size = 350;
-        m_assumed_chain_state_size = 6;
+        m_assumed_blockchain_size = 9;
```
Comment (BlockMechanic) [inline src/chainparams.cpp:158]: I think this is OK as a start. Future wallets, especially with the SPV drive may result in smaller numbers
